version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=databridgeuk

  omnidb:
    build: ./omnidb
    depends_on:
      - db
    ports:
      - 8080:8080
      - 25482:25482

  metabase:
    build: ./metabase
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  postgres_data:
