#category,description
cats = [
    'Leasing',
    'Dormant',
    'Household',
    'Organisations',
    'Office/Administration',
    'Real Estate',
    'Insurance',
    'Technology',
    'Legal',
    'Finance',
    'Retail',
    'Electricity/Electronics',
    'Packaging/Storage',
    'Waste',
    'Plastics',
    'Chemicals',
    'Tools/Furniture',
    'Media/Communications',
    'Medicine/Care/Security',
    'Entertainment/Leisure',
    'Education',
    'Transport',
    'Construction/Maintenance',
    'Wholesale',
    'Processing',
    'Manufacturing',
    'Paper',
    'Textiles/Fashion',
    'Oil/Gas/Mining/Extraction',
    'Consumables',
    'Plants/Animals/Fish',
    'Metals/Metal Products',
    'Non-Trading',
]
