category = (
    'Leasing',
    'Dormant',
    'Household',
    'Organisations',
    'Office/Administration',
    'Real Estate',
    'Insurance',
    'Technology',
    'Legal',
    'Finance',
    'Retail',
    'Electricity/Electronics',
    'Packaging/Storage',
    'Waste',
    'Plastics',
    'Chemicals',
    'Tools/Furniture',
    'Media/Communications',
    'Medicine/Care/Security',
    'Entertainment/Leisure',
    'Education',
    'Transport',
    'Construction/Maintenance',
    'Wholesale',
    'Processing',
    'Manufacturing',
    'Paper',
    'Textiles/Fashion',
    'Oil/Gas/Mining/Extraction',
    'Consumables',
    'Plants/Animals/Fish',
    'Metals/Metal Products',
    'Non-Trading',
)

title = {
        'companyname': 'Company Name',
        'companynumber': 'Companies House ID',
        'regaddress_careof': 'Who even wants to know this?!',
        'regaddress_pobox': 'PO Box',
        'regaddress_addressline1': 'Address Line 1',
        'regaddress_addressline2': 'Address Line 2',
        'regaddress_posttown': 'Town',
        'regaddress_county': 'County',
        'regaddress_country': 'Country',
        'regaddress_postcode': 'Postcode',
        'companycategory': 'Company Category',
        'companystatus': 'Company Status',
        'countryoforigin': 'Country of Origin',
        'dissolutiondate': 'Dissolution Date',
        'incorporationdate': 'Incorporation Date',
        'accounts_accountrefday': 'Account Ref Day',
        'accounts_accountrefmonth': 'Account Ref Month',
        'accounts_nextduedate': 'Accounts Next Due Date',
        'accounts_lastmadeupdate': 'Accounts Last Made Update',
        'accounts_accountcategory': 'Account Category',
        'returns_nextduedate': 'Returns Next Due Date',
        'returns_lastmadeupdate': 'Returns Last Made Update',
        'mortgages_nummortcharges': 'No. Mortgage Charges',
        'mortgages_nummortoutstanding': 'No. Mortgage Outstanding',
        'mortgages_nummortpartsatisfied': 'No. Mortgage Part Satisfied',
        'mortgages_nummortsatisfied': 'No. Mortgages Satisfied',
        'siccode_sictext_1': 'SIC Code 1',
        'siccode_sictext_2': 'SIC Code 2',
        'siccode_sictext_3': 'SIC Code 3',
        'siccode_sictext_4': 'SIC Code 4',
        'limitedpartnerships_numgenpartners': 'Number of General Partners ',
        'limitedpartnerships_numlimpartners': 'Number of Limited Partners',
        'url': 'Companies House URL',
        'previousname_1_condate': 'Change of Name Date 1',
        'previousname_1_companyname': 'Previous Company Name 1',
        'previousname_2_condate': 'Change of Name Date 2',
        'previousname_2_companyname': 'Previous Company Name 2',
        'previousname_3_condate': 'Change of Name Date 3',
        'previousname_3_companyname': 'Previous Company Name 3',
        'previousname_4_condate': 'Change of Name Date 4',
        'previousname_4_companyname': 'Previous Company Name 4',
        'previousname_5_condate': 'Change of Name Date 5',
        'previousname_5_companyname': 'Previous Company Name 5',
        'previousname_6_condate': 'Change of Name Date 6',
        'previousname_6_companyname': 'Previous Company Name 6',
        'previousname_7_condate': 'Change of Name Date 7',
        'previousname_7_companyname': 'Previous Company Name 7',
        'previousname_8_condate': 'Change of Name Date 8',
        'previousname_8_companyname': 'Previous Company Name 8',
        'previousname_9_condate': 'Change of Name Date 9',
        'previousname_9_companyname': 'Previous Company Name 9',
        'previousname_10_condate': 'Change of Name Date 10',
        'previousname_10_companyname': 'Previous Company Name 10',
        'confstmtnextduedate': 'Confirmation Statement Next Due Date',
        'confstmtlastmadeupdate': 'Confirmation Statement Last Made Up Date',
        'equity': 'Equity',
        'creditors': 'Creditors',
        'propertyplantequipment': 'Property Plant Equipment',
        'netassetsliabilities': 'Net Assets Liabilities',
        'netcurrentassetsliabilities': 'Net Current Assets Liabilities',
        'totalassetslesscurrentliabilities': 'Total Asset',
        'currentassets': 'Current Assets',
        'accumulateddepreciationimpairmentpropertyplantequipment': 'Accumulated Depreciation Impairment of Property Plant Equipment',
        'propertyplantequipmentgrosscost': 'Gross Cost of Property Plant Equipment',
        'debtors': 'Debtors',
        'averagenumberemployeesduringperiod': 'No. Employees',
        'cashbankonhand': 'Cash Bank on Hand',
        'fixedassets': 'Fixed Assets',
        'othercreditors': 'Other Creditors',
        'increasefromdepreciationchargeforyearpropertyplantequipment': 'Increase from Depreciation for Year Property Plant Equipment',
        'otherdebtors': 'Other Debtors',
        'tradedebtorstradereceivables': 'Trade Debtors/Trade Receivables',
        'tradecreditorstradepayables': 'Trade Creditors/Trade Payables',
        'othertaxationsocialsecuritypayable': 'Other Taxation Social Security Payable',
        'calledupsharecapitalnotpaidnotexpressedascurrentasset': 'Called Up Share Capital Not Expressed as Current Asset',
        'parvalueshare': 'Par Value Shatr',
        'provisionsforliabilitiesbalancesheetsubtotal': 'Provisions for Liabilities in Balance Sheet Subtotal',
        'totalinventories': 'Total Inventories',
        'totaladdsinclfrmbusincombopropertyplantequipment': 'Total Additions Including from Business Combinations Property Plant Equipment ',
        'corporationtaxpayable': 'Corporation Tax Payable',
        'accruedliabilitiesnotexpressedwithincreditorssubtotal': 'Accrued liabilities not Expressed within Creditor Subtotal',
        'numbersharesallotted': 'No. Shares Allotted',
        'amountspecificadvanceorcreditdirectors': 'Amount Specific Advance or Credit Directors',
        'prepaymentsaccruedincomenotexpressedwithincurrentassetsubtotal': 'Pre-Payments Accrued Income Not Expressed within Current Asset Subtotal',
        'intangibleassets': 'Intangible Assets',
        'bankborrowingsoverdrafts': 'Bank Borrowings Overdrafts',
        'numbersharesissuedfullypaid': 'No. Shares Issued Fully Paid',
        'additionsotherthanthrubusincombospropertyplantequipment': 'Additions other than through business combinations of Property Plant Equipment',
        'accruedliabilitiesdeferredincome': 'Accrued Liabilities Deferred Income',
        'financeleaseliabilitiespresentvaluetotal': 'Finance Lease liabilities',
        'taxationsocialsecuritypayable': 'Taxation Social Security Payable',
        'profitloss': 'Profit/Loss',
        'accumulatedamortisationimpairmentintangibleassets': 'Accumulated Amortisation Impairment of Intangible Assets',
        'disposalspropertyplantequipment': 'Disposals Property Plant Equipment',
        'intangibleassetsgrosscost': 'Intangible Assets Gross Cost',
        'accruedliabilities': 'Accrued Liabilities',
        'amountspecificadvanceorcreditrepaidinperioddirectors': 'Advance or Credit Repaid in Period Directors',
        'disposalsdecreaseindepreciationimpairmentpropertyplantequipment': 'Disposals Decrease in Depreciation Impairment of Property Plant Equipment',
        'amountspecificadvanceorcreditmadeinperioddirectors': 'Advance or Credit MAde in Period Directors',
        'advancescreditsdirectors': 'Advances in Credits to Directors',
        'futureminimumleasepaymentsundernon': 'Future Minimum Lease Payments',
        'investmentproperty': 'Investment Property',
        'investmentsfixedassets': 'Investment Property',
        'prepaymentsaccruedincome': 'Prepayments Accrued Income',
        'taxationincludingdeferredtaxationbalancesheetsubtotal': 'Taxation including Deferred Tax',
        'totalborrowings': 'Total Borrowing',
        'amountsowedtodirectors': 'Amount Owed to Directors',
        'bankborrowings': 'Bank Borrowing',
        'taxtaxcreditonprofitorlossonordinaryactivities': 'Tax Credit on Profit or Loss on Ordinary Activities',
        'turnoverrevenue': 'Turnover Revenue',
        'depreciationrateusedforpropertyplantequipment': 'Depreciation Rate Used for Property Plant Equipment',
        'dividendspaid': 'Dividends Paid',
        'advancescreditsmadeinperioddirectors': 'Advances in Credits Made in Period by Directors',
        'prepayments': 'Pre-payments',
        'increasefromamortisationchargeforyearintangibleassets': 'Increase from Amortisation Charge for Year Intangible Assets',
        'otherdisposalspropertyplantequipment': 'Other Disposals of Property Plant Equipment',
        'deferredincome': 'Deferred Income',
        'otherdspsalsdcrseindeprecimprmentprprtyplantequipment': 'Other Disposals of Decrease in Depreciation of Impairment of Property Plant Equipment',
        'administrationsupportaveragenumberemployees': 'Administration Support of of Average Number of Employess',
        'amountsowedtogroupundertakings': 'Amounts owed to Group Undertakings',
        'loansfromdirectors': 'Loans From Directors',
        'value': 'Value',
        'deferredtaxliabilities': 'Deferred Tax Liabilities',
        'otherremainingborrowings': 'Other Remaining Borrowings',
        'investmentpropertyfairvaluemodel': 'Investment Property Fair Value Model',
        'provisions': 'Provisions',
        'comprehensiveincomeexpense': 'Comprehensive ',
        'financeleasepaymentsowingminimumgross': 'Finance Lease Payments Owing Minimum Gross',
        'bankoverdrafts': 'Bank Overdrafts',
        'otherinvestmentsotherthanloans': 'Other Investments Other Than Loans',
        'nominalvalueallottedsharecapital': 'Nominal Value of Allotted Share Capital',
        'otheroperatingexpensesformat2': 'Other Operating Expenses Format',
        'investmentsingroupundertakings': 'Investments in Group Undertakings',
        'advancescreditsrepaidinperioddirectors': 'Advances Credits Repaid in Period Directors',
        'staffcostsemployeebenefitsexpense': 'Staff Costs Employee Benefits Expense',
        'profitlossonordinaryactivitiesbeforetax': 'Profit/Loss on Ordinary Activities Before Tax',
        'accdepnotincludimpairmentpropertyplantequipment': 'Accumulated Depreciation not including Impairment of Property Plant Equipment',
        'amountsowedbygroupundertakings': 'Amounts Owed by Group Undertakings',
        'recoverablevalue': 'Recoverable Value',
        'amountsowedbyrelatedparties': 'Amounts Owed by Related Parties',
        'rawmaterialsconsumablesused': 'Raw Materials Consumables Used',
        'netdeferredtaxliabilityasset': 'Net Deferred Tax Liability Assets',
        'corporationtaxrecoverable': 'Corporation Tax Recoverable',
        'furtheritemcreditorscomponenttotalcreditors': 'Further Item Creditors as a Component of Total Creditors',
        'calledupsharecapitalnotpaid': 'Called Up Share Capital Not Paid',
        'administrativeexpenses': 'Administrative Expenses',
        'workinprogress': 'Work in Progress',
        'operatingprofitloss': 'Operating Profit/Loss',
        'grossprofitloss': 'Gross Profit/Loss',
        'depreciationamortisationimpairmentexpense': 'Depreciation Amortisation Impairment Expense',
        'otheroperatingincomeformat2': 'Other Operating Income',
        'netassetsliabilitiesincludingpensionassetliability': 'Net Assets/Liabilities including Pension Asset/Liability',
        'cashbankinhand': 'Cash Bank in Hand',
        'currenttaxforperiod': 'Current Tax for Period',
        'currentassetinvestments': 'Current Asset Investments',
        'finishedgoodsgoodsforresale': 'Finished Goods/ Goods for Resale',
        'dividendspaidonshares': 'Dividends Paid on Shares',
        'directorremuneration': 'Director Remuneration',
        'shareholderfunds': 'Shareholder Funds',
        'merchandise': 'Merchandise',
        'investments': 'Investments',
        'costsales': 'Cost Sales',
        'sharecapitalallottedcalleduppaid': 'Shared Capital Allotted Called up Paid',
        'otherinventories': 'Other Inventories',
        'issueequityinstruments': 'Issue Equity Instruments',
        'cashcashequivalents': 'Cash and Cash Equivalents',
        'investmentsinsubsidiaries': 'Investments in Subsidiaries',
        'interestpayablesimilarchargesfinancecosts': 'Interest Payable Similar Charges Finance Costs',
        'charityfunds': 'Charity Funds',
        'salesmarketingdistributionaveragenumberemployees': 'Sales Marketing Distribution by Average Number of Employee',
        'totalincreasedecreasefromrevaluationspropertyplantequipment': 'Total Change from Revaluations of Property Plant Equipment',
        'otherinterestreceivablesimilarincomefinanceincome': 'Other Interest Receivables Similar to Income Finance Income',
        'incomeexpenserecogniseddirectlyinequity': 'Income Expense Recognised Directly in Equity',
        'depreciationexpensepropertyplantequipment': 'Depreciation Expense of Property Plant Equipment',
        'furtherdepitemavgnoemployeescomponentaveragenumberlist': 'Further Department item Average Number of Employees Component Average Number List',
        'incdecrinntdeftxlbilityfrmamountrecognisedinprfitorlss': 'Change In Net Deferred Tax Liability from Amount recognised in Profit or Loss',
        'amountsrecoverableoncontracts': 'Amounts Recoverable on Contracts',
        'furtheritemdebtorscomponenttotaldebtors': 'Further Item Debtors as a Component of Total Debtors',
        'rawmaterials': 'Raw Materials',
        'finishedgoods': 'Finished Goods',
        'amountsowedtogroupundertakingsparticipatinginterests': 'Amounts Owed to Group Undertakings Participating Interests',
        'incrsedcrseduetotrnsfrsbtwnclassespropertyplantequipment': 'Change Due to Transfer between Classes Property Plant Equipment',
        'financialassets': 'Financial Assets',
        'distributioncosts': 'Distribution Costs',
        'deferredtaxassetdebtors': 'Deferred Tax Asset Debtors',
        'amountsowedtorelatedparties': 'Amounts Owed to Related Parties',
        'rawmaterialsconsumables': 'Raw Materials Consumables',
        'totaladditionsincludingfrombusinesscombinationsintangibleassets': 'Total Additions Including for Business Combinations of Intangible Assets',
        'percentageclassshareheldinsubsidiary': ' Percentage Class Share Held in Subsidary',
        'balancesamountsowedtorelatedparties': 'Balance Amounts Owed to Related Parties',
        'addsotherthanthrubusincombosinvstmntproprtyfairvaluemodel': 'Additions Other than Through Business Combinations of Investment Property ',
        'additionalprovisionsincreasefromnewprovisionsrecognised': 'Additional Provisions Increase From New Provisions Recognised',
        'furtheritemtaxincreasedecreasecomponentadjustingitems': 'Further Item Tax Change as Component of Adjusting Items',
        'deftaxexpensecreditrelatingtoorigintionreversltimingdiffs': 'Deferred Tax Expense relating to origination reversal timing differences',
        'dividendpersharefinal': 'Dividends per Share Final',
        'costcharitableactivity': 'Cost of Charitable Activity',
        'totalliabilities': 'Total Liabilities',
        'totalassets': 'Total Assets',
        'otherpayablesaccruedexpenses': 'Other Payable Accrued Expenses',
        'increasedecreaseinpropertyplantequipment': 'Increase Decrease in Property Plant Equipment',
        'donationslegacies': 'Donation Legacies',
        'finaldividendspaid': 'Final dividends Paid',
        'increasedecreaseindepreciationimpairmentpropertyplantequipment': 'Change in Depreciation of Impairments in Property Plant Equipment',
        'auditfeesexpenses': 'Audit Fees Expenses',
        'amountsowedbygroupundertakingsparticipatinginterests': 'Amounts Owed by Group Undertakings in Participating Interests',
        'taxexpensecreditapplicabletaxrate': 'Tax Expense of Credit Applicable Tax Rate',
        'netincomexpndbeftrnsfrsbtwnfndsotherrcognisedgainslsses': 'Net Income Expenditure Before transfers Between Other Recognised Gains/Losses',
        'increasedecreaseincurrenttaxfromadjustmentforpriorperiods': 'Change In Current Tax from Adjustments For prior Periods',
        'additionsotherthanthroughbusinesscombinationsintangibleassets': 'Additions Other than Through Business Combinations of Intangible Assets',
        'capitalemployed': 'Capital Employed',
        'calledupsharecapital': 'Called Up Share Capital',
        'otheroperatingincomeformat1': 'Other Operating Income Format',
        'incomeendowments': 'Income Endowments',
        'expenditure': 'Expenditure',
        'costsraisingfunds': 'Costs Raising Funds',
        'totalcurrenttaxexpensecredit': 'Total Current Tax Expense Credit',
        'dividendpershareinterim': 'Dividend Per Share Interim',
        'crryingamntundercostmodelrevaluedassetspropertyplantequipment': 'Carrying amount under Cost Model Revalued Assets of Property Plant Equipment',
        'calledupsharecapitalnot': 'Called Up Share Capital Not',
        'addprovincreasefromnewprovrecognisedinprofitorloss': 'Addition Provisions Increase from New Provisions Recognised in P/L',
        'dividenddeclaredpayable': 'Dividend Declared Payable',
        'capitalcommitments': 'Capital Commitments',
        'wagessalaries': 'Wages/Salaries',
        'paymentstorelatedparties': 'Payments to Related Parties',
        'nominalvaluesharesissuedspecificshareissue': 'Nominal Value of Shares Issued Specific Share Issue',
        'investmentincome': 'Investment Income',
        'interimdividendspaid': 'Interim Dividends Paid',
        'frthritemincdecrinequitytotalincomxpnsercognseddirctlyinquity': 'Further Item Change in Equity as a component of Total Income Expense Recognised Directly in Equity',
        'amountsowedbyassociates': 'Amounts Owed by Associates',
        'socialsecuritycosts': 'Social Security Costs',
        'paymentsreceivedonaccount': 'Payments Received on Accounts',
        'incomefromothertradingactivities': 'Income From Other Trading Activities',
        'incomefromcharitableactivity': 'Income from Charitable Activity',
        'disposalsinvestmentpropertyfairvaluemodel': 'Disposals Investment Property Fair Value Model',
        'disposalsintangibleassets': 'Disposals Intangible Assets',
        'pensionotherpost': 'Pension Other Post',
        'dividendspaidonsharesinterim': 'Dividends Paid on Shares Interim',
        'disposalsdecreaseinamortisationimpairmentintangibleassets': 'Disposals Decrease in Amortisation from Impairment of intangible assets',
        'transferstofromretainedearningsincreasedecreaseinequity': 'Transfer to/from retained earnings from a change in equity',
        'profitlossonordinaryactivitiesaftertax': 'Profit/Loss on Ordinary Activites After Tax',
        'otherincrsedecrseindeptionimprmentprprtyplantequipment': 'Other Change in Depreciation of Impairment of Property Plant Equipment',
        'numbersharesissuedspecificshareissue': 'No. Shares Issued Specific Share Issue',
        'numbersharesissuedbutnotfullypaid': 'No. Shares Issued but not Fully Paid',
        'incomefromrelatedparties': 'Income from Related Parties',
        'amortisationrateusedforintangibleassets': 'Amortisation Rate Used for Intangible Assets',
        'transfersbetwnppeclassesincreasedecrindeprimpairment': 'Transfers between ppe classes from a change in depreciation impairment',
        'gnlssonrvltionprpertyplnteqpmentbfortxinothrcomprehincme': 'Gain/Loss on revaluation Property Plant Equipment before tax in other comprehensive income',
        'gainlossonremeasurementdfndbnftplnsbfrtxinothrcomprehincome': 'Gain/Loss on remeasurement Define Benefit Plans before Tax in Other Comprehensive Income',
        'deferredtaxassets': 'Deferred Tax Assets',
        'carryingamountpropertyplantequipmentwithrestrictedtitle': 'Carrying Ammount of Property Plant Equipment with Restricted Title',
        'balancesamountsowedbyrelatedparties': 'Balances Amounts Owed by Related Parties',
        'applicabletaxrate': 'Applicable Tax Rate',
        'keymanagementpersonnelcompensationtotal': 'Key Management Personnel Compensation Total',
        'incrsdcseindeftxlbilityfromamountrecognisedinprofitorloss': 'Change in Deferred Tax Liability from Amount Recognised in P/L',
        'financialliabilities': 'Financial Liabilities',
        'totaloperatingleasepayments': 'Total Operating Lease Payments',
        'productionaveragenumberemployees': 'No. Employees',
        'numberdirectorsaccruingbenefitsundermoneypurchasescheme': 'Number of Directors Accruing Benefits Under Money Purchases Scheme',
        'loansowedtorelatedparties': 'Loans Owed to Related Parties',
        'increasedecreasefromfrvaluadjstmntinvstmntprprtyfrvluemdel': 'Change from Value Adjustments investment Property Fair Value Model',
        'amountsowedtootherrelatedpartiesotherthandirectors': 'Amounts Owed to Other Related Parties Other than Directors',
        'amountsowedbydirectors': 'Amounts Owed by Directors',
        'accumulatedamortisationnotincludingimpairmentintangibleassets': 'Accumulated Amortisation Not including Impairment of Intangible Assets',
        'unpaidcontributionstopensionschemes': 'Unpaid Contributions to Pension Schemes',
        'interestincomeonbankdeposits': 'Interest Income on Bank Deposits',
        'incometaxexpensecreditoncomponentsothercomprehensiveincome': 'Income Tax Expense Credit on Components Other Comprehensive Income',
        'companycontributionstomoneypurchaseplansdirectors': 'Company Contributions to Money Purchase Plans Directors',
        'usefullifeintangibleassetsyears': 'Useful Life Intangible Assets Year',
        'txincrdecrfromefectexpensesnotdctindeterintxableproforloss': 'Tax Change from effect expenses not deductible in determining taxable P/L',
        'revenuefromsalegoods': 'Revenue from Sale Goods',
        'ownshares': 'Own Shares',
        'interestexpnsonobligtionsunderfinleasehirepurchcntrcts': 'Interest expense on Obligations Under Finance Lease Hire Repurchase Contracts',
        'incomematerialfund': 'Income Material Fund',
        'governmentgrantspayable': 'Government Grants Payable',
        'inothercomprehincomepretaxcmpntttlothercompincomepretax': 'Further Item Gain/Loss In Other Comprehensive Income Pre-Tax as a Component of Total Other Comprehensive Income Pre-Tax ',
        'financialcommitmentsotherthancapitalcommitments': 'Financial Commitments Other than Capital Commitments',
        'expenditurematerialfund': 'Expenditure material Fund',
        'directorremunerationbenefitsincludingpaymentstothirdparties': 'Director Remuneration Benefits Including Payments to Third Parties',
        'creditorsduewithinoneyear': 'Creditors Due Within One Year',
        'amountsowedbyassociatesjointventuresparticipatinginterests': 'Amounts Owed by Associates Joint Ventures Participating Interests',
        'otherdeferredtaxexpensecredit': 'Other Deferred Tax Expense Credit',
        'netassetsliabilitiessubsidiaries': 'Net Assets Liabilities Subsidiaries',
        'issuebonussharesdecreaseincreaseinequity': 'Issue Bonus Shares Decrease/Increase Inequality',
        'investmentsinjointventures': 'Investments in Joint Ventures',
        'investmentsingroupundertakingsparticipatinginterests': 'Investments in Group Undertakings Participating Interests',
        'gainlossondisposalspropertyplantequipment': 'Gain/Loss on Disposables Property Plant Equipment',
        'balanceswithbanks': 'Balances With Banks',
        'totaldeferredtaxexpensecredit': 'Total Deferred Tax Expense Credit',
        'taxincreasedecreasefromeffectcapitalallowancesdepreciation': 'Tax Increase Decrease from Effective Capital Allowances Depreciation',
        'profitlosssubsidiaries': 'Profit/Loss Subsidiaries',
        'pensioncostsdefinedcontributionplan': 'Pension Cost Defined Contribution Plan',
        'othercurrentassetinvestmentsbalancesheetsubtotal': 'Other Currents Asset Investment Balance Sheet Subtotal',
        'numbersharesauthorised': 'No. Shares Authorised',
        'heritageassets': 'Heritage Assets',
        'gainlossduetoforeignexchangedifferencesrecognisedinprofitorloss': 'Gain/Loss Due to Foreigh Exchange Differences Recognised in Profit/Loss',
        'Furtheriteminterestexpensecomponenttotalinterestexpense': 'Further Item Interest Expense Component Total Interest Expense',
        'itmincreasedecreaseininvestmentpropertyfrvalumodelcorrespttl': 'Item Change in investment property from value model corresponding total',
        'gainlssinothercomprehincomenttxcmpnttotalothercomprencomenttx': 'Further Item Gain/loss in other Comprehensive income Net Tax As a Component of Total Other Comprehensive Income Net Tax',
        'cumulativepreferencesharedividendsunpaid': 'Cumulative Preferences Share Dividends Unpaid',
        'totalincreasedecreasefromrevaluationsintangibleassets': 'Total Increased From Revaluations Intangible Assets',
        'otheroperatingincome': 'Other Operating Income',
        'otherloansclassifiedunderinvestments': 'Other Loans Classified Under Investments',
        'othercrditorsincltxtionscialsecurtyblncesheetsubtotal': 'Other Creditos Including Taxation on Social Security Balance Sheet Subtotal',
        'investmentsinsubsidiariesmeasuredfairvalue': 'Investments in Subsidiaries Measured Fair Value',
        'investmentsinassociates': 'Investments in Associates',
        'employeestotal': 'No. Employees',
        'decreaseinloansowedtorelatedpartiesduetoloansrepaid': 'Decrease In Loans Owed to Related Parties Due to Loads Replaid',
        'companycontributionstodefinedbenefitplansdirectors': 'Company Contributions to Defined Benefit Plans Directors',
        'cashonhand': 'Cash on Hand',
        'weightedaverageexercisepriceequityinstrumentsoutstandingshare': 'Weighted Average Exercise Price Equity instruments Outstanding share',
        'usefullifepropertyplantequipmentyears': 'Useful Life Property Plant Equipment Years',
        'revlutionsincrsedecrseindprctionimprmntpropertyplnteqpmnt': 'Revaluations Change in Depreciation Impairment of Property Plant Equipment',
        'pensioncostsdefinedbenefitplan': 'Pension Costs Defined Benefit Plan',
        'otherprovisionsbalancesheetsubtotal': 'Other Provisions Balance Sheet Subtotal',
        'otherinterestincome': 'Other Interest Income',
        'otherinterestexpense': 'Other Interest Expense',
        'otherincreasedecreaseinamortisationimpairmentintangibleassets': 'Other Change In Amortisation Impairment of intangible Assets',
        'otherdebtorsbalancesheetsubtotal': 'Other Debtors Balance Sheet Subtotal',
        'othercomprehensiveincomeexpensebeforetax': 'Other Comprehensive Income Expense Before Tax',
        'operatingleasepaymentsowing': 'Operating Lease Payments Owing',
        'numberequityinstrumentsoutstandingshare': 'No. Equity instruments Outstanding Share',
        'numberemployeesdate': 'No. Employees',
        'netcashgeneratedfromoperations': 'Net Cash Generated From Operations',
        'loanstogroupundertakingsparticipatinginterests': 'Loans to Group Undertakings Participating Interests',
        'loansowedbyrelatedparties': 'Loads Owed by Related Parties',
        'interestexpenseonbankoverdraftsbankloanssimilarborrowings': 'Interest Expense on Bank Overdraft',
        'interestexpenseonbankoverdrafts': 'Interest Expense on Bank Overdraft',
        'interestexpenseonbankloanssimilarborrowings': 'Interest Expense on Bank Loans/Similar Borrowings',
        'increasedecreaseduetotransfersbetweenclassesintangibleassets': 'Change due to Transfer between Classes of intangible assets',
        'gainlossonrvaluationprprtyplnteqpmentnttxinthercmprehincme': 'Gain/Loss on Revaluation of Property Plant Equipment Net Tax In Other Comprehensive Income',
        'itmincmefrmothertrdingactvtiestotalmfrmothertradingactivities': 'Further Item Income from other Trading Activities as a Component of Total Income From other Trading Activities',
        'furtheritemdonationslegaciescomponenttotaldonationslegacies': 'Further Item Donations Legacies as a Component of total Donations legacies',
        'dividendspaidonsharesfinal': 'Dividends Paid on Shares Final',
        'depreciationamortisationexpense': 'Depreciation Amortisation Expense',
        'capitalisedborrowingcostsrelatedtopropertyplantequipment': 'Capitalised Borrowing Costs Related to Property Plant Equipment',
        'capitalreductiondecreaseinequity': 'Capital Reduction Decreaser in Equity',
        'amountsowedbyotherrelatedpartiesotherthandirectors': 'Amounts Owed By Other Related Parties Other Than Directors',
        'amortisationexpenseintangibleassets': 'Amortisation Expense of Intangible Assets',
        'taxincreasedecreasearisingfromgrouprelieftaxreconciliation': 'Tax Change from Group Relief Tax Reconciliation',
        'paymentsonaccountinventories': 'Payments on Account Inventories',
        'ownershipinterestinsubsidiarypercent': 'Ownership interest in subsidiary percent',
        'otherexpenditure': 'Other Expenditure',
        'numbersharesissuedinperiod': 'No. Shares Issued in Period',
        'nominalvaluesharesissuedinperiod': 'Nominal Value of Shares Issued in Period',
        'interestexpenseonpreferencesharesclassifiedasdebt': 'interest Expense on Preference Shares Classified as Debt',
        'increaseinloansowedbyrelatedpartiesduetoloansadvanced': 'Increase in Loans by Related Parties Due to Loans Advanced',
        'increasedecreaseinstocksinventoriesfinishedgoodsworkinprogress': 'Change in Stocks Inventories Finished Goods Work in Progress',
        'increasedecreaseduetotransfersintooroutpropertyplantequipment': 'Change Due to Transfers Into or Out of Property Plant Equipment',
        'transferstofromnon': 'Transfers to/from non',
        'Trnsfrsintopropertyplantequipmentincrecrindeimprment': 'Transfer into or out Property Plant Equipment/ Increase/Decrease in Depreciation Impairment',
        'taxationcomplianceservicesfees': 'Taxation Compliance Services Fees',
        'taxincreasedecreasefromothershort': 'Tax Increase/Decrease from Other Short',
        'taxincreasedecreasefromeffectunrelievedtaxlossescarriedforward': 'Tax Increase/Decrease from Effect Unrelieved Tax Losses Carried Forward',
        'taxincreasedecreasefromeffectforeigntaxrates': 'Tax Increase Decrease from Effect Foreign Tax Rates',
        'txincdecrfrmffctxpnssntddctiblefrtaxotherthngdwllamortimprmen': 'Tax Increase/Decrease from Effect Expenses not Deductible for Tax Purposes Other than Goodwill/ amortisation Impairment',
        'txincrsdecrsefromffectadjstmntinresrchdevtaxcredit': 'Tax Increase/Decrease from Effect Adjustment in Researched Development Tax Credit',
        'taxdecreaseincreasefromeffectrevenueexemptfromtaxation': 'Tax Decrease/Increase from Affect Revenue Exempt from Taxation',
        'researchdevelopmentexpenserecognisedinprofitorloss': 'Research and Development Expense Recognised in Profit/Loss',
        'researchdevelopmentaveragenumberemployees': 'Research and Development No. Employees',
        'redeemablepreferencesharesliability': 'Redeemable Preference Shares Liabilities',
        'purchasepropertyplantequipment': 'Purchase Property Plant Equipment',
        'profitlossattributabletoownersparent': 'Profit/Loss Attributable to Owners Parent',
        'presentvaluefinanceleasereceivables': 'Present Value Finance Lease Receivables',
        'percentageclassshareheldinjointventure': 'Percentage Class Share Held in Joint Venture',
        'pensionschemesprepayments': 'Pension Schemes Prepayments',
        'paymentsfinanceleaseliabilitiesclassifiedasfinancingactivities': 'Payments/ Finance Lease Liabilities Classified as Financing Activities',
        'outstandingpre': 'Outstanding Pre',
        'othertaxationpayable': 'Other Taxations Payable',
        'othernon': 'Other Non',
        'otherincreasedecreaseinnetdeferredtaxliability': 'Other Increase/Decrease in Net Deferred Tax Liability',
        'othergeneralgrants': 'Other General Grants',
        'otherdisposalsinvestmentpropertyfairvaluemodel': 'Other Disposals Investment Property Fair Value Model',
        'netinterestreceivedpaidclassifiedasinvestingactivities': 'Net Interest Received/ Paid Classified as Investing Activities ',
        'netfinanceincomecosts': 'Net Finance Income Costs',
        'netcashflowsfromusedinoperatingactivities': 'Net Cash Flows from used in Operating Activities',
        'netcashflowsfromusedininvestingactivities': 'Net Cash Flows from Used in Investing Activities',
        'netcashflowsfromusedinfinancingactivities': 'Net Cash Flows From used in Financing Activities ',
        'loansfromgroupundertakingsparticipatinginterests': 'Loans from Group Undertakings/ Participating Interests',
        'liabilitiessecuredbyassets': 'Liabilities Secured by Assets',
        'investmentsinassociatesjointventuresparticipatinginterests': 'Investments in Associates Joint Ventures/ Participating Interests',
        'interestpaidclassifiedasoperatingactivities': 'Interest Pain Classified as Operating Activities',
        'interestincomefromgroupundertakingsparticipatinginterests': 'Interest Income From Group Undertakings/ Participating Interests ',
        'interestexpenseondebtsecuritiesinissueothersimilarloans': 'Interest Expense on Debt Securities in Issue/ Other Similar Loans',
        'increaseinloansowedtorelatedpartiesduetoloansadvanced': 'Increase in Loans Owed to Related Parties Due to Loans Advanced',
        'increasedecreaseinprovisionsthroughtransfersreclassifications': 'Increase/Decrease in Provisions Though Transfer Reclassifications',
        'increasedecreaseinexistingprovisions': 'Increase/Decrease in Existing Provisions',
        'incrdecrincashbeforeexchangedifferenceschangesinconsolidation': 'Increase/Decrease in Cash Before Exchanged Difference Changes in Consolation',
        'incometaxespaidrefundclassifiedasoperatingactivities': 'Income Taxes Paid/ Refund Classified as Operating Activities',
        'incomefromothertradingactivity': 'Income from Other Trading Activity',
        'incomefromcharitableactivities': 'Income from Charitable Activities',
        'impairmentlosspropertyplantequipment': 'Impairment Loss Property Plant Equipment',
        'giftaid': 'Gift Aid',
        'gainlssonrvluationotherasstsnttxinothercmprehensveincome': 'Gain/Loss on Revaluation/ Other Assets/ Net Tax in Other Comprehensive Income',
        'gainlossondisposalsothernon': 'Gain/Loss on Disposals/ Other Non',
        'gainlossincashflowsfromchangeindebtorstradeotherreceivables': 'Gain/Loss in Cash Flows from Change in Debtors Trade/ Other Receivables',
        'gainlossincashflowsfromchangeincreditorstradeotherpayables': 'Gain/Loss in Cash Flows from Change in Creditors Trade/ Other Payables',
        'futurefinancechargesonfinanceleases': 'Future Finance Charges on Finance Leases',
        'furtherrentalleasingincomeitemcomponenttotalrentalleasingincome': 'Further Rental Leasing Income Item Component Total Rental/Leasing Income',
        'furtheroperatingexpenseitemcomponenttotaloperatingexpenses': 'Further Operating Expense Item Component Total Operating Expenses',
        'itemoperatingxpnslossincmesttmntitemcomponentopratngproftlss': 'Further Item Operating Expense Loss Income Statement Item Component Operating Profit/Loss',
        'fundraisingsupportcosts': 'Fundraising Support Costs',
        'feesfornon': 'Fees for Non',
        'donatedgoodsfacilitiesservices': 'Donated Goods/ Facilities/ Services',
        'dividendsproposedbutnotpaid': 'Dividends Proposed but Not Paid',
        'dividendspaidclassifiedasfinancingactivities': 'Dividends Paid Classified as Financing Activities',
        'dividendincomefromgroupundertakings': 'Dividend Income from Group Undertakings',
        'deferredtaxexpensecreditrelatingtochangesintaxratesorlaws': 'Deferred Tax Expense Credit Relating to Changes in Tax Rates or Laws',
        'decreaseinloansowedbyrelatedpartiesduetoloansrepaid': 'Decrease in Loads Owed by Related Parties Due to Loans Repaid',
        'debenturesinissue': 'Debentures in Issue',
        'currentliabilities': 'Current Liabilities',
        'considerationreceivedforsharesissuedspecificshareissue': 'Consideration Received for Shares Issued/ Specific Share Issue',
        'amountsowedtoparententities': 'Amounts Owed to Parent Entities',
        'amountsowedtoassociatesjointventuresparticipatinginterests': 'Amounts Owed to Associates Joint Ventures/ Participating Interests',
        'amountsowedtoassociates': 'Amounts Owed to Associates',
        'amountsowedbyjointventures': 'Amounts Owed by Joint Ventures',
        'amountpaidliabilityincurredinfulfillingguaranteesdirectors': 'Amounts Paid Liability Incurred in Fulfilling Guarantees Directors',
        'advancesoninvoicediscountingfacilities': 'Advances on Invoice Discounting Facilities',
        'accruedincome': 'Accrued Income',
        'weightedaverageexercisepriceequityinstrumentsforfeitedshare': 'Weighted Average Exercise Price Equity Instruments for Forfeited Share',
        'weightedaverageexercisepriceequityinstrumentsexpiredshare': 'Weighted Average Exercise Price Equity Instruments Expired Share',
        'unusedprovisionreversed': 'Unused Provisions Reversed',
        'totaladditionsheritageassets': 'Total Additions Heritage Assets',
        'taxincreasedecreasefromtransferpricingadjustments': 'Tax Increase/Decrease from Transfer Pricing Adjustment',
        'redemptionsharesdecreaseinequity': 'Redemption Shares Decrease in Equity ',
        'provisionsused': 'Provisions Used',
        'othertaxationadvisoryservicesfees': 'Other Taxation Advisory Service Fees',
        'otherexternalcharges': 'Other External Charges',
        'othercurrenttaxexpense': 'Other Current Tax Expense',
        'numberequityinstrumentsforfeitedshare': 'No. Equity Instruments Forfeited Share',
        'numberequityinstrumentsexpiredshare': 'No. Equity Instruments Expired Share',
        'investmentsinotherentitiesmeasuredfairvalue': 'Investments in Other Entities Measured Fair Value',
        'intrstexpnseonfinanciallbilitiesfrvluethruprftorlss': 'Interest Expense on Financial Liabilities Fair Value Through Profit/Loss',
        'governmentgrantincome': 'Government Grant Income',
        'gainlossfromfrvaluadjstmntinvstmentpropertyrecgnsedinprftlss': 'Gain/Loss From Fair Value Adjustment Investment Property Recognised In Profit/Loss',
        'dividendrecommendedbydirectors': 'Dividends Recommended by Directors',
        'dividendpershareproposedbutnotpaid': 'Dividends Per Share Proposed but Not Paid',
        'derivativeliabilities': 'Derivative Liabilities',
        'deferredtaxexpensecreditfromunrecognisedtaxlossorcredit': 'Deferred Tax Expense Credit From Unrecognised Tax Loss or Credit',
        'valueaddedtaxpayable': 'Value Added Tax Payable',
        'recoverablevalueaddedtax': 'Recoverable Value Added Tax',
        }

  




