# Generated by Django 3.0.6 on 2020-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accounts_lastmadeupdate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='accounts_nextduedate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='confstmtlastmadeupdate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='confstmtnextduedate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='dissolutiondate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='incorporationdate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_10_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_1_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_2_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_3_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_4_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_5_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_6_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_7_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_8_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previousname_9_condate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='returns_lastmadeupdate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='returns_nextduedate',
            field=models.DateTimeField(blank=True),
        ),
    ]
