# Generated by Django 3.0.6 on 2020-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200519_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='returns_lastmadeupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
