# Generated by Django 3.0.6 on 2020-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200519_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accounts_accountrefday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='accounts_accountrefmonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='limitedpartnerships_numgenpartners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='limitedpartnerships_numlimpartners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mortgages_nummortcharges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mortgages_nummortoutstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mortgages_nummortpartsatisfied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mortgages_nummortsatisfied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
